name: Build and publish docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax      - name: Build docs

      - name: Install prereqs
        run: |
          pip install sphinx

      - name: Run build
        run: |
          make dirhtml

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: build/dirhtml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
